services:
  node1:
    build: .
    command: -addr "node1:8080"

  node2:
    build: .
    command: -addr "node2:8080" -peer "node1:8080"

  node3:
    build: .
    command: -addr "node3:8080" -peer "node1:8080"

  node4:
    build: .
    command: -addr "node4:8080" -peer "node1:8080"
